"""workspace_logto_org

Revision ID: 091d244c00b3
Revises: 26f9727fbf76
Create Date: 2026-07-08 10:54:59.059882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '091d244c00b3'
down_revision: Union[str, None] = '26f9727fbf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('logto_organization_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'logto_organization_id')
    # ### end Alembic commands ###
