"""workspace_scim_token

Revision ID: 26f9727fbf76
Revises: 991f2c638207
Create Date: 2026-07-08 10:52:20.910267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26f9727fbf76'
down_revision: Union[str, None] = '991f2c638207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('scim_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'scim_token_hash')
    # ### end Alembic commands ###
