"""workspace_retention

Revision ID: 991f2c638207
Revises: cce840e50683
Create Date: 2026-07-08 10:48:18.974673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '991f2c638207'
down_revision: Union[str, None] = 'cce840e50683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'retention_days')
    # ### end Alembic commands ###
