"""workspace_model_policy

Revision ID: cce840e50683
Revises: 11664112c0d7
Create Date: 2026-07-07 16:31:24.450862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cce840e50683'
down_revision: Union[str, None] = '11664112c0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('allowed_models', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('local_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'local_only')
    op.drop_column('workspaces', 'allowed_models')
    # ### end Alembic commands ###
